trigger:
  branches:
    include:
      - "main"

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - template: .azure/pipelines/lint.yml

  - template: .azure/pipelines/build.yml

  - template: .azure/pipelines/deploy.yml
    parameters:
      environment: development

  - template: .azure/pipelines/deploy.yml
    parameters:
      environment: test

  - template: .azure/pipelines/deploy.yml
    parameters:
      environment: production
